ParcelMeadowHut_MapScripts::
	.byte 0


ParcelMeadowHut_Note::
# 7 "data/maps/ParcelMeadowHut/scripts.pory"
	msgbox ParcelMeadowHut_Note_Text_0, MSGBOX_SIGN
	end


ParcelMeadowHut_Note_Text_0:
# 7 "data/maps/ParcelMeadowHut/scripts.pory"
	.string "A feeding chart, in marker:\p"
	.string "DODUO -- anything. SHROOMISH -- don't.\n"
	.string "SEEDOT -- pretends it doesn't eat.\p"
	.string "LOTAD -- pool. CARVANHA -- POOL,\n"
	.string "CAREFULLY. NUMEL -- warm sand, will not\l"
	.string "move for food.\p"
	.string "ELECTRIKE -- catch it first.$"
